global using Microsoft.AspNetCore.Mvc;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Filesharing.Models;
global using Microsoft.AspNetCore.Authorization;
global using Filesharing.Data;
global using System.Security.Claims;